# Copyright 2014-2015 by Cloudsoft Corporation Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sudo: false

script: mvn clean install

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "eixhldm0eCdKfO37uru2qpLRv22liokwd7HaY2JkJqx1LonDM25uWWJ2a51HLSDClt3PYdLzKRXPtsLWCNlGxzlbSjXngsANXg/LIG8aoyyJdk4Hg+oNZW/LI1cDb7iUQyV1xVkKbRIOPuEAZEPIc4kOYTqTRenncCYVrXaeHAk="
    - secure: "EG+DuKB4+LwaOuPa8GOdjqPyfKfGjsCs677nQgKX9+PSn0c3Dw6kOweeCK8CSvQIhADs+oPOoqUFCAMu2kvrpsISsmWZJBtoM4JLAM7o6XKNKdqdBm1T/ZMuftaes16w4BLTTa0rBwJKNdcIHggnSh9ws7CbkbDBbTglOGNpJV8="

cache:
  directories:
    - $HOME/.m2
notifications:
  email:
  - andrew.kennedy@cloudsoft.io
  - andrea.turli@cloudsoft.io
  